#include "core/exporter.h"

#include "core/mpfrref.h"
#include "ui/formatting.h" // hexPattern, decimalLiteral

#include <algorithm>
#include <cinttypes>
#include <cstdio>
#include <sstream>

namespace ulpscope {

namespace {

// fmt is passed in rather than read from the result so these helpers stay
// usable when formatting a table the UI is about to build.
std::string hexOf(uint64_t bits, const FloatFormat &fmt) {
  return hexPattern(bits, fmt);
}

} // namespace

std::string exportTable(const ScanResult &result, const ExportOptions &opts) {
  const std::string fn =
      opts.functionName.empty() ? result.config.symbol : opts.functionName;
  const FloatFormat &fmt = result.config.fmt;
  const std::string pad(opts.indentSpaces, ' ');

  std::ostringstream o;
  o << "// Regression vectors for " << fn << " (" << fmt.describe() << ").\n"
    << "// Generated by ulpscope. " << result.mismatchCount << " of "
    << result.total << " inputs differ from the correctly rounded result"
    << (result.config.toleranceUlp
            ? " by more than " + std::to_string(result.config.toleranceUlp) +
                  " ULP"
            : std::string())
    << "; worst is " << result.maxUlp << " ULP at input "
    << hexOf(result.maxUlpAtBits, fmt) << ".\n"
    << "//\n"
    << "// Inputs and expectations are given as bit patterns so that denormals,\n"
    << "// signed zeros and NaNs survive the round trip intact.\n\n"
    << "#include <stdint.h>\n"
    << "#include <stdio.h>\n"
    << "#include <string.h>\n\n"
    << "extern " << fn << "(" << (result.config.nargs > 1 ? "double, " : "")
    << "double);\n\n"
    << "struct " << fn << "_case {\n"
    << pad << "uint32_t in;\n"
    << pad << "uint32_t expect;\n"
    << pad << "const char *name;\n"
    << pad << "const char *value;\n"
    << "};\n\n"
    << "static const struct " << fn << "_case cases[] = {\n";

  // Worst first; fall back to a spread of passing cases when everything passes,
  // so the test still pins down behaviour rather than being empty.
  std::vector<const Sample *> chosen;
  if (!result.worst.empty()) {
    chosen = result.worst;
  } else if (opts.includePassingCases) {
    const size_t stride = std::max<size_t>(
        1, result.samples.size() / std::max<uint64_t>(1, opts.maxCases));
    for (size_t i = 0; i < result.samples.size() && chosen.size() < opts.maxCases;
         i += stride)
      chosen.push_back(&result.samples[i]);
  }
  if (chosen.size() > opts.maxCases)
    chosen.resize(opts.maxCases);

  for (const Sample *s : chosen) {
    o << pad << pad << "{" << hexOf(s->inputBits, fmt) << ", "
      << hexOf(s->expectedBits, fmt) << ", \""
      << className(fmt.classify(s->inputBits)) << " " << hexOf(s->inputBits, fmt)
      << "\", " << decimalLiteral(s->input) << "},\n";
  }

  o << "};\n\n"
    << "int main(void) {\n"
    << pad << "unsigned i, failures = 0;\n"
    << pad << "for (i = 0; i < sizeof(cases) / sizeof(cases[0]); ++i) {\n"
    << pad << pad << "float in, got;\n"
    << pad << pad << "uint32_t inbits, gotbits;\n"
    << pad << pad << "memcpy(&inbits, &cases[i].in, 4);\n"
    << pad << pad << "in = (float)inbits;\n"
    << pad << pad << "got = (float)" << fn << "(";
  for (int a = 0; a < result.config.nargs; ++a)
    o << (a ? ", in" : "in");
  o << ");\n"
    << pad << pad << "memcpy(&gotbits, &got, 4);\n"
    << pad << pad << "if (gotbits != cases[i].expect) {\n"
    << pad << pad << pad << "++failures;\n"
    << pad << pad << pad
    << "printf(\"%s(%s) = %08\" PRIx32 \", want %08\" PRIx32 \"\\n\",\n"
    << pad << pad << pad << pad
    << "       cases[i].name, cases[i].value, gotbits, cases[i].expect);\n"
    << pad << pad << "}\n"
    << pad << "}\n"
    << pad << "printf(\"%u/%u failures\\n\", failures, (unsigned)"
    << " (sizeof(cases) / sizeof(cases[0])));\n"
    << pad << "return failures != 0;\n"
    << "}\n";

  return o.str();
}

std::string exportLit(const ScanResult &result, const ExportOptions &opts) {
  const std::string fn =
      opts.functionName.empty() ? result.config.symbol : opts.functionName;
  const FloatFormat &fmt = result.config.fmt;
  const std::string pad(opts.indentSpaces, ' ');

  std::ostringstream o;
  o << "// RUN: %clang %s -o %t %s\n"
    << "// RUN: %t\n\n"
    << "// Generated by ulpscope: inputs where " << fn << " (" << fmt.name
    << ") is not correctly rounded.\n"
    << "// " << result.mismatchCount << " mismatches, worst " << result.maxUlp
    << " ULP.\n\n"
    << "#include \"src/math/fputil/FPUtil.h\"\n"
    << "#include \"src/math/SupportConfig.h\"\n"
    << "#include \"src/__support/FPUtil/FEnvImpl.h\"\n"
    << "#include <cmath>\n"
    << "#include <limits>\n\n"
    << "extern " << fn << "(" << (result.config.nargs > 1 ? "double, " : "")
    << "double);\n\n"
    << "TEST(" << fn << "Ulpscope) {\n"
    << pad << "static const uint32_t inputs[] = {\n";
  for (size_t i = 0; i < result.worst.size() && i < opts.maxCases; ++i)
    o << pad << pad << hexOf(result.worst[i]->inputBits, fmt) << ", ";
  o << "};\n"
    << pad << "static const uint32_t expected[] = {\n";
  for (size_t i = 0; i < result.worst.size() && i < opts.maxCases; ++i)
    o << pad << pad << hexOf(result.worst[i]->expectedBits, fmt) << ", ";
  o << "};\n\n"
    << pad
    << "for (unsigned i = 0; i < sizeof(inputs) / sizeof(*inputs); ++i) {\n"
    << pad << pad << "uint32_t in = inputs[i];\n"
    << pad << pad << "double x = FPBitsToDouble<double>(in);\n"
    << pad << pad << "double got = " << fn << "(";
  for (int a = 0; a < result.config.nargs; ++a)
    o << (a ? ", x" : "x");
  o << ");\n"
    << pad << pad << "EXPECT_EQ(FPBitsToDouble<double>(expected[i]), got);\n"
    << pad << "}\n"
    << "}\n";

  return o.str();
}

std::string exportCsv(const ScanResult &result, uint64_t maxCases) {
  const FloatFormat &fmt = result.config.fmt;
  std::ostringstream o;
  o << "input_bits,input_hex,input,class,expected_bits,expected,actual_bits,"
       "actual,ulp_error,mismatch\n";
  uint64_t n = 0;
  for (const Sample *s : result.worst) {
    if (n++ >= maxCases)
      break;
    o << s->inputBits << ',' << hexOf(s->inputBits, fmt) << ','
      << decimalLiteral(s->input) << ','
      << className(fmt.classify(s->inputBits)) << ',' << s->expectedBits << ','
      << decimalLiteral(s->expected) << ',' << s->actualBits << ','
      << decimalLiteral(s->actual) << ','
      << (s->nanDisagreement ? std::string("nan") : std::to_string(s->ulpError))
      << ',' << (s->mismatch ? 1 : 0) << '\n';
  }
  return o.str();
}

} // namespace ulpscope